from typing import Mapping, NamedTuple


class Section(NamedTuple):
    id: int
    name: str
    time: str
    location: str


class LabSection(NamedTuple):
    id: int
    name: str
    time: str
    location: str


class Student(NamedTuple):
    sid: str
    canvas_id: int
    sortable_name: str
    name: str
    email: str
    section_id: int | None
    lab_section_id: int | None
    status: str


class Assignment(NamedTuple):
    id: str
    canvas_id: int
    gradescope_id: int | None
    title: str
    type: str
    max_points: float | None


class Submission(NamedTuple):
    sid: str
    assignment_id: str
    total_score: float | None
    status: str
    submission_id: int | None
    submission_time: str
    lateness: str
    view_count: int | None
    submission_count: int | None
    last_updated: str


class Grade(NamedTuple):
    sid: str
    assignment_id: str
    score: float | None
    comments: str | None


class GradeOperation(NamedTuple):
    id: int
    sid: str
    assignment_id: str
    type: str
    priority: int
    parameters: str
    policy: str | None


class Question(NamedTuple):
    id: str
    assignment_id: str
    title: str | None
    max_points: float


class RubricItem(NamedTuple):
    id: str
    assignment_id: str
    question_id: str
    rubric_idx: int
    description: str | None


class QuestionScore(NamedTuple):
    sid: str
    question_id: str
    score: float
    adjustment: float | None
    comments: str | None
    grader: str | None
    tags: str | None


class RubricItemApplied(NamedTuple):
    sid: str
    assignment_id: str
    rubric_id: str


class Operation(NamedTuple):
    """An operation generated by a policy before it is persisted."""

    sid: str
    assignment_id: str
    parameters: Mapping[str, object]


TABLE_NAMES = {
    Section: "sections",
    LabSection: "lab_sections",
    Student: "students",
    Assignment: "assignments",
    Submission: "submissions",
    Grade: "grades",
    GradeOperation: "grade_operations",
    Question: "questions",
    RubricItem: "rubric_items",
    QuestionScore: "question_scores",
    RubricItemApplied: "rubric_items_applied",
}
